### ISSUE TITLE
How you test your awesome model on MTEB leaderboard? 

### ISSUE THREAD

**Issue by YuboFeng2023** [kongds/scaling_sentemb#2]
Dear authors,

What a fabulous sentence embedding model you have created!
As a sentence embedding researcher, we would like to know your model's performance on the [MTEB Leaderboard](https://huggingface.co/spaces/mteb/leaderboard), which is a well-known sentence embedding benchmark.

Best wishes!

**Comment by kongds** [comment]
Thank you for your interest in our paper.

We did not evaluate our models on MTEB because our model mainly focuses on embeddings sentence (including the design of the prompt). MTEB is a general text-embedding benchmark that includes tasks such as passage embedding (like NQ). Additionally, due to the slow inference speed of LLMs, evaluation could be also time-consuming to run the whole MTEB.

However, we also welcome to reproduce our models on MTEB.
